// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovimentosManuais.Infra.Repository.DataBaseConfig;

namespace MovimentosManuais.Infra.Repository.Migrations
{
    [DbContext(typeof(MovimentacoesManuaisContext))]
    partial class MovimentacoesManuaisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("MovimentosManuais.Domain.MovimentacaoManual", b =>
                {
                    b.Property<int>("NumeroLancamento")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Num_Lancamento");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Dat_Mes");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Dat_Ano");

                    b.Property<string>("CodigoProduto")
                        .HasColumnType("char(4)")
                        .HasColumnName("Cod_Produto");

                    b.Property<string>("CodigoCosif")
                        .HasColumnType("char(11)")
                        .HasColumnName("Cod_Cosif");

                    b.Property<string>("CodigoUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Cod_Usuario");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("Dat_Movimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Des_Descricao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Val_Valor");

                    b.HasKey("NumeroLancamento", "Mes", "Ano", "CodigoProduto", "CodigoCosif");

                    b.HasIndex("CodigoProduto", "CodigoCosif");

                    b.ToTable("Movimento_Manual");
                });

            modelBuilder.Entity("MovimentosManuais.Domain.Produto", b =>
                {
                    b.Property<string>("CodigoProduto")
                        .HasColumnType("char(4)")
                        .HasColumnName("Cod_Produto");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Des_Produto");

                    b.Property<string>("Status")
                        .HasColumnType("char(1)")
                        .HasColumnName("Sta_Status");

                    b.HasKey("CodigoProduto");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("MovimentosManuais.Domain.ProdutoCosif", b =>
                {
                    b.Property<string>("CodigoProduto")
                        .HasColumnType("char(4)")
                        .HasColumnName("Cod_Produto");

                    b.Property<string>("CodigoCosif")
                        .HasColumnType("char(11)")
                        .HasColumnName("Cod_Cosif");

                    b.Property<string>("CodigoClassificacao")
                        .HasColumnType("char(6)")
                        .HasColumnName("Cod_Classifcacao");

                    b.Property<string>("Status")
                        .HasColumnType("char(1)")
                        .HasColumnName("Sta_Status");

                    b.HasKey("CodigoProduto", "CodigoCosif");

                    b.ToTable("Produto_Cosif");
                });

            modelBuilder.Entity("MovimentosManuais.Domain.MovimentacaoManual", b =>
                {
                    b.HasOne("MovimentosManuais.Domain.ProdutoCosif", "ProdutoCosif")
                        .WithMany()
                        .HasForeignKey("CodigoProduto", "CodigoCosif")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoCosif");
                });

            modelBuilder.Entity("MovimentosManuais.Domain.ProdutoCosif", b =>
                {
                    b.HasOne("MovimentosManuais.Domain.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
